### ISSUE TITLE
infografia TypeScript

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Sandoval6#1]
[infografia_charly.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Sandoval6/files/15204988/infografia_charly.pdf)

**Comment by josealfredo79** [comment]
calificacion..????

**Comment by josealfredo79** [comment]
Se necesita la calificación 19
